name: Build and push docker nightly

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'release/nightly/temp, default is nightly'
        required: true
        default: 'nightly'
  workflow_call:
    inputs:
      mode:
        description: 'release/nightly/temp, default is nightly'
        type: string
        required: true
        default: 'nightly'
      arch:
        description: 'which images to build [ cpu, cpu-full, pytorch-inf2, pytorch-gpu, tensorrt-llm, lmi, aarch64]'
        type: string
        required: false
        default: '["cpu", "cpu-full", "pytorch-inf2", "pytorch-gpu", "tensorrt-llm", "lmi", "aarch64"]'
  schedule:
    - cron: '0 13 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  create-runners:
    runs-on: [ self-hosted, scheduler ]
    strategy:
      matrix:
        arch: ${{ fromJson(inputs.arch) }}
    steps:
      - name: Create new CPU instance
        if: matrix.arch != 'aarch64'
        id: create_cpu
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          token=$( curl -X POST -H "Authorization: token ${{ secrets.ACTION_RUNNER_PERSONAL_TOKEN }}" \
          https://api.github.com/repos/deepjavalibrary/djl-serving/actions/runners/registration-token \
          --fail \
          | jq '.token' | tr -d '"' )
          ./start_instance.sh action_cpu $token djl-serving
          instance_id=`grep "instance_id=" $GITHUB_OUTPUT | cut -d'=' -f2`
          echo "instance_id_${{matrix.arch}}=$instance_id" >>"$GITHUB_OUTPUT"

      - name: Create Graviton instance
        if: matrix.arch == 'aarch64'
        id: create_graviton
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          token=$( curl -X POST -H "Authorization: token ${{ secrets.ACTION_RUNNER_PERSONAL_TOKEN }}" \
          https://api.github.com/repos/deepjavalibrary/djl-serving/actions/runners/registration-token \
          --fail \
          | jq '.token' | tr -d '"' )
          ./start_instance.sh action_graviton $token djl-serving
          instance_id=`grep "instance_id=" $GITHUB_OUTPUT | cut -d'=' -f2`
          echo "instance_id_${{matrix.arch}}=$instance_id" >>"$GITHUB_OUTPUT"

    outputs:
      instance_id_cpu: ${{ steps.create_cpu.outputs.instance_id_cpu }}
      instance_id_cpu-full: ${{ steps.create_cpu.outputs.instance_id_cpu-full }}
      instance_id_pytorch-inf2: ${{ steps.create_cpu.outputs.instance_id_pytorch-inf2 }}
      instance_id_pytorch-gpu: ${{ steps.create_cpu.outputs.instance_id_pytorch-gpu }}
      instance_id_tensorrt-llm: ${{ steps.create_cpu.outputs.instance_id_tensorrt-llm }}
      instance_id_lmi: ${{ steps.create_cpu.outputs.instance_id_lmi }}
      instance_id_aarch64: ${{ steps.create_cpu.outputs.instance_id_aarch64 }}

  nightly-build:
    needs: create-runners
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(inputs.arch) }}
    runs-on:
      - self-hosted
      - instance_id_${{ matrix.arch }}
      - RUN_ID-${{ github.run_id }}
      - RUN_NUMBER-${{ github.run_number }}
      - SHA-${{ github.sha }}
    steps:
      - name: Clean disk space
        run: |
          sudo rm -rf \
          /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
          $AGENT_TOOLSDIRECTORY
      - uses: actions/checkout@v4
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: install awscli
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185921645874:role/github-actions-djl-serving
          aws-region: us-east-1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Extract DJL and DJL Serving versions from TOML
        id: get-versions
        run: |
          DJL_VERSION=$(awk -F '=' '/djl / {gsub(/ ?"/, "", $2); print $2}' gradle/libs.versions.toml)
          SERVING_VERSION=$(awk -F '=' '/serving / {gsub(/ ?"/, "", $2); print $2}' gradle/libs.versions.toml)
          echo "DJL_VERSION=$DJL_VERSION" >> $GITHUB_ENV
          echo "SERVING_VERSION=$SERVING_VERSION" >> $GITHUB_ENV
      - name: Build serving package for nightly
        if: ${{ inputs.mode == '' || inputs.mode == 'nightly' }}
        run: |
          ./gradlew --refresh-dependencies :serving:dockerDeb -Psnapshot
      - name: Build and push nightly docker image
        if: ${{ inputs.mode == '' || inputs.mode == 'nightly' }}
        working-directory: serving/docker
        run: |
          export NIGHTLY="-nightly"
          docker compose build --no-cache \
          --build-arg djl_version=${{ env.DJL_VERSION }}-SNAPSHOT \
          --build-arg djl_serving_version=${{ env.SERVING_VERSION }}-SNAPSHOT \
          ${{ matrix.arch }}
          docker compose push ${{ matrix.arch }}
      - name: Build and push temp image
        if: ${{ inputs.mode == 'temp' }}
        working-directory: serving/docker
        run: |
          export NIGHTLY="-nightly"
          docker compose build --no-cache \
          --build-arg djl_version=${{ env.DJL_VERSION }}-SNAPSHOT \
          --build-arg djl_serving_version=${{ env.SERVING_VERSION }}-SNAPSHOT \
          ${{ matrix.arch }}
          repo="185921645874.dkr.ecr.us-east-1.amazonaws.com/djl-ci-temp"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $repo
          tempTag="$repo:${{ matrix.arch }}-${GITHUB_SHA}"
          docker tag deepjavalibrary/djl-serving:${{ matrix.arch }}-nightly $tempTag
          docker push $tempTag
      - name: Build and push release docker image
        if: ${{ inputs.mode == 'release' }}
        working-directory: serving/docker
        run: |
          export BASE_RELEASE_VERSION="${{ env.SERVING_VERSION }}"
          export RELEASE_VERSION="${{ env.SERVING_VERSION }}-"
          docker compose build --no-cache \
          --build-arg djl_version=${{ env.DJL_VERSION }} \
          --build-arg djl_serving_version=${{ env.SERVING_VERSION }} \
          ${{ matrix.arch }}
          docker compose push ${{ matrix.arch }}
      - name: Retag image for release
        if: ${{ matrix.containers.name == 'cpu' && inputs.mode == 'release' }}
        working-directory: serving/docker
        run: |
          docker tag deepjavalibrary/djl-serving:${{ env.SERVING_VERSION }} deepjavalibrary/djl-serving:latest
          docker push deepjavalibrary/djl-serving:latest
  stop-runners:
    if: always()
    runs-on: [ self-hosted, scheduler ]
    needs: [nightly-build, create-runners]
    steps:
      - name: Stop all instances
        run: |
          cd /home/ubuntu/djl_benchmark_script/scripts
          ids=${{ toJson(needs.create-runners.outputs) }}
          instance_id=${{ needs.create-runners.outputs.cpu_instance_id_1 }}
          ./stop_instance.sh $instance_id
          instance_id=${{ needs.create-runners.outputs.cpu_instance_id_2 }}
          ./stop_instance.sh $instance_id
          instance_id=${{ needs.create-runners.outputs.cpu_instance_id_3 }}
          ./stop_instance.sh $instance_id
          instance_id=${{ needs.create-runners.outputs.cpu_instance_id_4 }}
          ./stop_instance.sh $instance_id
          instance_id=${{ needs.create-runners.outputs.cpu_instance_id_5 }}
          ./stop_instance.sh $instance_id
          instance_id=${{ needs.create-runners.outputs.cpu_instance_id_6 }}
          ./stop_instance.sh $instance_id
          instance_id=${{ needs.create-runners.outputs.graviton_instance_id_1 }}
          ./stop_instance.sh $instance_id