on: issue_comment

jobs:
  pr_commented_build:
    name: PR comment
    if: ${{ github.event.issue.pull_request && startsWith( github.event.comment.body, 'test1')}}
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      PR_CONTEXT: ${{ toJson(github.event.issue.pull_request) }}
    steps:
      - run: |
          echo $GITHUB_CONTEXT 
          echo $PR_CONTEXT

        env:
          NUMBER: ${{ github.event.issue.number }}